version: '3.7'
services:
  db:
    container_name: database-postgre
    image: postgres
    restart: always
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - my_net
  
  server:
    container_name: rust-web-dev
    image: rust-web-dev
    env_file: .env
    depends_on:
      - db
    networks:
      - my_net
    ports:
      - '3030:3030'

networks:
  my_net:
    driver: brigde
volumes:
  data: