apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
      name: myapp
    spec:
      containers:
        - name: myapp
          image: rust-web-dev
          imagePullPolicy: Never
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
          ports:
            - containerPort: 3030 
          volumeMounts:
            - name: rust-dev-env
              mountPath: /home
          args:
            - source /home/env && sleep 100

      volumes:
        - name: rust-dev-env
          secret:
            defaultMode: 420
            secretName: rust-dev-env

---

apiVersion: v1
kind: Service
metadata:
  name: svc-myapp
  labels:
    service: svc-myapp
spec:
  selector:
    app: myapp
  ports:
    - port: 3030
      targetPort: 3030
